name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Give execute permission to mvnw
        run: chmod +x mvnw

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: purvakamerkarjj5499079/spring-app
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Deploy (optional)
#        run: |
#          # Example: Deploy to Kubernetes
#          kubectl apply -f k8s/spring-app-deployment.yaml
